# Generated by Django 4.0.3 on 2022-04-10 13:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Forthall_Gym', '0003_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='Description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
