# Generated by Django 4.0.3 on 2022-04-10 14:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Forthall_Gym', '0005_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=70)),
                ('Description', tinymce.models.HTMLField(null=True)),
                ('Subtitle', models.CharField(max_length=70)),
                ('Subdescr', tinymce.models.HTMLField(null=True)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Step1', tinymce.models.HTMLField(null=True)),
                ('Step2', tinymce.models.HTMLField(null=True)),
                ('Step3', tinymce.models.HTMLField(null=True)),
            ],
        ),
    ]
