# Generated by Django 4.0.3 on 2022-04-10 14:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Forthall_Gym', '0007_history_minidesc_alter_history_step1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=70)),
                ('Description', tinymce.models.HTMLField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='Minidesc',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Step1',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Step2',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Step3',
        ),
    ]
