# Generated by Django 4.0.3 on 2022-04-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forthall_Gym', '0008_step_remove_history_minidesc_remove_history_step1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Subtitle',
            new_name='Subtitle1',
        ),
        migrations.AddField(
            model_name='history',
            name='Subtitle2',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
