# Generated by Django 4.0.3 on 2022-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forthall_Gym', '0012_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Workout',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
